version: '3.8'
services:
  web:
    build: ./web-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mlclient
    env_file:
      - ./web-app/.env  # Path to your .env file for the web service

  mlclient:
    build: ./machine-learning-client
    ports:
      - "5001:5001"
    depends_on:
      - db
    env_file:
      - ./machine-learning-client/.env  # Path to your .env file for the ML client

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
