version: '3.8'
services:
  web:
    build: ./web-app
    ports:
      - "5000:5000"
    depends_on:
      - db

  mlclient:
    build: ./machine-learning-client
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
