name: ML Client Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Machine Learning Client
    - name: Set up Python for ML Client
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies for ML Client
      run: |
        cd machine-learning-client
        pip install --upgrade pip
        pip install pipenv
        pipenv lock

    - name: Build ML Client Docker image
      run: |
        cd machine-learning-client
        docker build -t ml-client .

    # Assuming you don't actually want to run the container as part of CI
    # since it produces an output file and does not serve HTTP content
    # If you need to run it and perform actions, uncomment the following lines:
    # - name: Run ML Client Docker container
    #   run: |
    #     docker run --name ml-client ml-client
    #     docker cp ml-client:/app/output_audio.wav .
    #     docker rm ml-client

    # Web App
    - name: Build Web App Docker image
      run: |
        docker build -t webapp ./web-app

    # Assuming you want to start the web app container as part of the test
    - name: Run Web App Docker container
      run: |
        docker run --name my-webapp -d -p 8080:8080 webapp

    # Cleanup (if containers were run)
    - name: Cleanup Docker containers
      if: always()
      run: |
        docker stop my-webapp ml-client || true
        docker rm my-webapp ml-client || true
